### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null  

### ISSUE THREAD

**Issue by draschke** [6of5/UI5SplitApp-Boilerplate#5]
Hi 6of5,

after the installation I get this error. "Uncaught TypeError: Cannot read property 'length' of null.
I'm new in javascript, but I think it has something to do with cssRules, because it is null.

![image](https://cloud.githubusercontent.com/assets/4199123/9504930/92ed53c8-4c3f-11e5-988b-3d4286279bf4.png)

![image](https://cloud.githubusercontent.com/assets/4199123/9504811/ed8ea878-4c3e-11e5-8425-b311e29700e1.png)
"

**Comment by 6of5** [comment]
Hi draschke,

the error is due to bug in the latest openui5 version (v1.28.16). Please see
[https://github.com/SAP/openui5/issues/578](https://github.com/SAP/openui5/issues/578)

if you use the v1.28.15 instead of the latest in the sapui5 bootstrap
src="https://openui5.netweaver.ondemand.com/1.28.15/resources/sap-ui-core.js"
then the issue should be gone

BR, HP

**Comment by 6of5** [comment]
I made an update, so that UI5BP is now using the version v1.28.15 instead of the latest, which is currently buggy.

Have fun with UI5BP and have also a look at the UI5BP Fiori Edition (which probably has the same issue in the moment :)

**Comment by 6of5** [comment]
so I close the ticket

**Comment by draschke** [comment]
Thanks for the quick response and thanks for your great work! :+1: 
I really appreciate it!
